version: '3.4'

services:
  sourcingdb:
    container_name: sourcingdb
    restart: always
    volumes:
        - ${APPDATA}/site:/data/db}
    ports:
        -  "27017:27017"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  sourcingsqldb:
    container_name: sourcingsqldb   
    ports:
        - "5434:1433"
    environment:
        - SA_PASSWORD="test123"
        - ACCEPT_EULA="Y""

       
  esourcing.product:
    container_name: esourcingproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      - "ProductDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
    depends_on:
        - sourcingdb
    ports:
      - "8000:80"  
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/http:ro

      - ${APPDATA}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
  esourcing.sourcing:
    container_name: esourcingsourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on:
        - sourcingdb
        - rabbitmq
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/http:ro

      - ${APPDATA}/.microsoft/usersecrets/:/root/.microsoft/usersecrets

  esourcing.order:
        container_name: esourcingorder
        environment:
         - ASPNETCORE_ENVIRONMENT=Development
         - "ConnectionStrings:OrderConnection=Server=sourcingsqldb;Database=OrderDb;User Id=sa;Password=Odb12345678"
         - "EventBus:HostName=rabbitmq"
        depends_on:
         - sourcingsqldb
         - rabbitmq
        volumes:
          - ${APPDATA}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
          - ${APPDATA}/.aspnet/https:/root/.aspnet/https/
        ports:
          - "8002:80"
    
  esourcing.apigateway:
        container_name: esourcingapigateway
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
          - esourcing.product
          - esourcing.sourcing
          - esourcing.order
        ports:
          - "5000:80"
        volumes:
          - ${APPDATA}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
          - ${APPDATA}/.aspnet/https:/root/.aspnet/https/
